<?php

namespace Style34\Form\Profile;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class RegistrationForm
 * @package Style34\Form
 */
class RegistrationForm extends AbstractType {

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
	public function buildForm(FormBuilderInterface $builder, array $options) {
		parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
	}
}