doctrine:
    dbal:
        default_connection: eryseClient
        connections:
            eryseClient:
                url: '%env(resolve:ERYSE_CLIENT_DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '12.0'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            eryseServer:
                url: '%env(ERYSE_SERVER_DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '12.0'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        default_entity_manager: eryseClient
        entity_managers:
            eryseClient:
                connection: eryseClient
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Client:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Model/Client'
                        prefix: 'EryseClient\Model\Client'
                        alias: EryseClient
            eryseServer:
                connection: eryseServer
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Server:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Model/Server'
                        prefix: 'EryseClient\Model\Server'
                        alias: EryseServer
