parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: eryseClient
        connections:
            eryseClient:
                url: '%env(resolve:ERYSE_CLIENT_DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '9.6.11'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            eryseServer:
                url: '%env(ERYSE_SERVER_DATABASE_URL)%'
                driver: 'pdo_pgsql'
                server_version: '9.6.11'
                charset: utf8
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        default_entity_manager: eryseClient
        entity_managers:
            eryseClient:
                connection: eryseClient
                mappings:
                    Client:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Client'
                        prefix: 'EryseClient\Entity\Client'
                        alias: EryseClient
            eryseServer:
                connection: eryseServer
                mappings:
                    Server:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Server'
                        prefix: 'EryseClient\Entity\Server'
                        alias: EryseServer