scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken

    google:
        enabled: true
        template: Profile/Login/two-step-auth.html.twig

    trusted_device:
        enabled: true
        #        manager: style34.services.trusted_device_service  # Use a custom trusted device manager
        lifetime: 5184000
        extend_lifetime: false         # Automatically extend lifetime of the trusted cookie on re-login
        cookie_name: trusted_device    # Name of the trusted device cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
        cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax", "strict" or null