security:

    providers:
      main_db_provider:
        entity:
          class: Style34\Entity\Profile\Profile
          property: email


    encoders:
        Style34\Entity\Profile\Profile:
          algorithm: bcrypt
          cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~