security:

    providers:
      main_db_provider:
        entity:
          class: Style34\Entity\Profile\Profile
          property: email


    encoders:
        Style34\Entity\Profile\Profile:
          algorithm: bcrypt
          cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
              login_path: profile-login
              check_path: profile-login
              username_parameter: _auth
              csrf_token_generator: security.csrf.token_manager
#              default_target_path: after_login_route_name

            logout:
              path:   profile-logout

            remember_me:
              secret:   '%kernel.secret%'
              lifetime: 604800 # 1 week in seconds
              path:     /