security:

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    role_hierarchy:
        ROLE_BANNED: ROLE_USER

        ROLE_INACTIVE: ROLE_USER
        ROLE_VERIFIED: ROLE_INACTIVE
        ROLE_MEMBER: ROLE_VERIFIED

        ROLE_MODERATOR: ROLE_MEMBER
        ROLE_ADMIN: ROLE_MODERATOR

    providers:
        in_memory: { memory: ~ }

        user-provider:
            id: EryseClient\Server\User\Security\Provider\UserProvider

    encoders:
        EryseClient\Server\User\Entity\UserEntity:
            algorithm: auto
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user-provider
            anonymous: true
            guard:
                authenticators:
                    - EryseClient\Server\User\Security\Authenticator\UserLoginFormAuthenticator
                provider: user-provider

            form_login:
                provider: user-provider
                login_path: user-security-login
                check_path: user-security-login
                username_parameter: _auth
                csrf_token_generator: security.csrf.token_manager
                #default_target_path: after_login_route_name

            logout:
                path:   user-security-logout

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 31536000 # 1 year in seconds
                path:     /
                token_provider: 'security.rememberme.token.provider.doctrine'

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
        # Ensure that authenticator page is accessible only when authentification is in progress
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
