security:

    providers:
        in_memory: { memory: ~ }

        user-provider:
            id: EryseClient\Security\UserProvider

    encoders:
        EryseClient\Entity\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:

            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                provider: user-provider

            logout_on_user_change: true
            anonymous: true
            guard:
                authenticators:
                    - EryseClient\Security\LoginFormAuthenticator
                provider: user-provider

            form_login:
                provider: user-provider
                login_path: security-login
                check_path: security-login
                username_parameter: _auth
                csrf_token_generator: security.csrf.token_manager
                #default_target_path: after_login_route_name

            logout:
                path:   security-logout

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 31536000 # 1 year in seconds
                path:     /
                token_provider: 'security.rememberme.token.provider.doctrine'

    access_control:
        # Ensure that authenticator page is accessible only when authentification is in progress
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
