security:
    role_hierarchy:
        ROLE_SERVER_BANNED: ROLE_BANNED

        ROLE_VERIFIED: ROLE_INACTIVE
        ROLE_MEMBER: ROLE_VERIFIED

        ROLE_MODERATOR: ROLE_MEMBER
        ROLE_ADMIN: ROLE_MODERATOR

    providers:
        in_memory: { memory: ~ }

        profile-provider:
            id: EryseClient\Client\ProfileSecurity\Provider\ProfileProvider

        user-provider:
            id: EryseClient\Server\UserSecurity\Provider\UserProvider

    encoders:
        EryseClient\Server\User\Entity\User:
            algorithm: auto
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                provider: profile-provider

            provider: user-provider
            anonymous: true
            guard:
                authenticators:
                    - EryseClient\Server\UserSecurity\Authenticator\UserLoginFormAuthenticator
                provider: user-provider

            form_login:
                provider: user-provider
                login_path: EryseClient\Server\UserSecurity\Authenticator\UserLoginFormAuthenticator::ROUTE
                check_path: EryseClient\Server\UserSecurity\Authenticator\UserLoginFormAuthenticator::ROUTE
                username_parameter: _auth
                csrf_token_generator: security.csrf.token_manager
                #default_target_path: after_login_route_name

            logout:
                path:   security-logout

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 31536000 # 1 year in seconds
                path:     /
                token_provider: 'security.rememberme.token.provider.doctrine'

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SECURE_SCHEME)%' }
        # Ensure that authenticator page is accessible only when authentification is in progress
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
