version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: memcached

    redis:
      image: redis:alpine
      container_name: redis

    postgres:
      image: postgres:9.6-alpine
      container_name: postgres
      working_dir: /application
      ports:
        - "5455:5432"
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=style34

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@style34.net}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - postgres
      restart: unless-stopped

    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8989:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: