version: "3.1"
services:

    # Memcached
    # ------------------------------------------------------------------------------------------------------------------
    memcached:
      image: memcached:alpine
      container_name: ec-memcached

    # Redis
    # ------------------------------------------------------------------------------------------------------------------
    redis:
      image: redis:alpine
      container_name: ec-redis

    # Postgres
    # ------------------------------------------------------------------------------------------------------------------
    postgres:
      image: postgres:9.6-alpine
      container_name: ec-postgres
      working_dir: /application
      ports:
        - "5455:5432"
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=style34

    # pgAdmin
    # ------------------------------------------------------------------------------------------------------------------
    pgadmin:
      image: dpage/pgadmin4
      container_name: ec-pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@EryseClient.net
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "5050:80"
      restart: unless-stopped
      depends_on:
        - "postgres"

    # nginx web server
    # ------------------------------------------------------------------------------------------------------------------
    webserver:
      build: phpdocker/nginx
      container_name: ec-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8001:8001"
      depends_on:
       - "php-fpm"

    mailcatcher:
      image: yappabe/mailcatcher
      container_name: ec-mailcatcher
      ports:
        - 1025:1025
        - 1080:1080

    # PHP-FPM
    # ------------------------------------------------------------------------------------------------------------------
    php-fpm:
      build: phpdocker/php-fpm
      container_name: ec-php-fpm
      working_dir: /application
      links:
        - mailcatcher
        - redis
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

volumes:
  postgres:
  pgadmin: