version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: style34-memcached

    redis:
      image: redis:alpine
      container_name: style34-redis

    postgres:
      image: postgres:9.6-alpine
      container_name: style34-postgres
      working_dir: /application
      ports:
        - "5455:5432"
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=style34

    webserver:
      image: nginx:alpine
      container_name: style34-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8989:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: style34-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

