version: "3.1"
services:

    # Memcached
    # ------------------------------------------------------------------------------------------------------------------
    memcached:
      image: memcached:alpine
      container_name: memcached

    # Redis
    # ------------------------------------------------------------------------------------------------------------------
    redis:
      image: redis:alpine
      container_name: redis

    # Postgres
    # ------------------------------------------------------------------------------------------------------------------
    postgres:
      image: postgres:9.6-alpine
      container_name: postgres
      working_dir: /application
      ports:
        - "5455:5432"
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=style34

    # pgAdmin
    # ------------------------------------------------------------------------------------------------------------------
    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@style34.net}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "5050:80"
      restart: unless-stopped
      depends_on:
        - "postgres"

    # nginx web server
    # ------------------------------------------------------------------------------------------------------------------
    webserver:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8989:80"

    # PHP-FPM
    # ------------------------------------------------------------------------------------------------------------------
    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

volumes:
  postgres:
  pgadmin: