# Eryse ACP configurations
parameters:
    eryse:
        client:
            name: '%env(resolve:ERYSE_CLIENT_NAME)%'
            emails:
                info: '%env(resolve:ERYSE_EMAIL_INFO)%'
                admin: '%env(resolve:ERYSE_EMAIL_ADMIN)%'
            membership:
                price: '%env(resolve:ERYSE_MEMBERSHIP_PRICE)%'

        server:
            name: '%env(resolve:ERYSE_SERVER_NAME)%'